import {
  sabreDesignAcornContainerImages,
  sabreDesignJapandiTrayImages,
  sabreDesignJunoTrayImages,
  sabreDesignMushroomContainerImages,
  sabreDesignPhoneStandImages,
} from "./sabredesign-media";
import type { StoreProduct } from "./types";

/**
 * Storefront fallbacks for approved listings that are not yet available from Stripe.
 * Stripe data wins whenever the test catalog is available.
 */
export const catalogPreviewProducts: StoreProduct[] = [
  {
    id: "local-preview-japandi-tray",
    slug: "japandi-tray",
    name: "Japandi Tray",
    description:
      "A low-profile catchall tray with a soft, sculptural edge for keys, jewelry, and the small things that deserve a calmer landing place.",
    category: "Home",
    colors: [
      "Matte Desert Tan (11401)",
      "Matte Dark Green (11501)",
      "Matte Ivory White (11100)",
      "Matte Dark Blue (11602)",
      "Matte Sakura Pink (11201)",
      "Matte Charcoal (11101)",
    ],
    featured: true,
    pickup: true,
    ship: true,
    stockStatus: "made_to_order",
    visibility: "public",
    photoReady: true,
    image: sabreDesignJapandiTrayImages[0],
    images: [...sabreDesignJapandiTrayImages],
    accent: "clay",
    colorHexes: ["#e8dbb7", "#68724d", "#ffffff", "#042f56", "#e8afcf", "#000000"],
    detailCopy:
      "The Japandi Tray is a quiet, everyday organizer sized for a console, bedside table, or desk. Its low rim keeps small essentials in one place without making the surface feel busy.",
    highlights: [
      "Maker-listed size: 197 × 123 × 16 mm",
      "Creator profile reference: 1 plate · 2.1 hours",
      "Six selected Bambu PLA Matte color options",
      "Low-profile catchall for small everyday essentials",
    ],
    fitNote: "MakerWorld lists this tray at 197 × 123 × 16 mm. The creator's reference profile is one plate and about 2.1 hours.",
    material: "Bambu PLA Matte",
    finish: "Fine matte surface with softly rounded edges",
    care: "Wipe with a soft, damp cloth. Keep away from sustained heat and direct sunlight.",
    leadTime: "Printed to order in 3–5 business days",
    designerName: "SabreDesign",
    designerUrl: "https://makerworld.com/en/@SabreDesign",
    sourceModelUrl: "https://makerworld.com/en/models/2419531-japandi-tray#profileId-2805325",
    requiresCommercialLicense: true,
    licenseStatus: "active",
    demo: false,
    variants: [
      {
        priceId: "demo_japandi_tray",
        sizeLabel: "197 × 123 mm tray",
        unitAmount: 2000,
        currency: "usd",
        sku: "JTR-STANDARD",
        dimensions: "197 × 123 × 16 mm",
      },
    ],
  },
  {
    id: "local-preview-acorn-container",
    slug: "acorn-container",
    name: "Acorn Container",
    description:
      "A sculptural, screw-top storage piece with soft ribs and an unmistakably autumnal silhouette.",
    category: "Home",
    colors: ["Natural Acorn", "Caramel Acorn", "Terracotta Acorn", "Modern Acorn"],
    colorways: [
      {
        label: "Natural Acorn",
        baseColor: "Matte Desert Tan (11401)",
        baseHex: "#e8dbb7",
        capColor: "Matte Dark Brown (11801)",
        capHex: "#7d6556",
      },
      {
        label: "Caramel Acorn",
        baseColor: "Matte Caramel (11803)",
        baseHex: "#ae835b",
        capColor: "Matte Dark Brown (11801)",
        capHex: "#7d6556",
      },
      {
        label: "Terracotta Acorn",
        baseColor: "Matte Terracotta (11203)",
        baseHex: "#b15533",
        capColor: "Matte Dark Brown (11801)",
        capHex: "#7d6556",
      },
      {
        label: "Modern Acorn",
        baseColor: "Matte Ivory White (11100)",
        baseHex: "#ffffff",
        capColor: "Matte Charcoal (11101)",
        capHex: "#000000",
      },
    ],
    featured: false,
    pickup: true,
    ship: true,
    stockStatus: "made_to_order",
    visibility: "public",
    photoReady: true,
    image: sabreDesignAcornContainerImages[0],
    images: [...sabreDesignAcornContainerImages],
    accent: "moss",
    colorHexes: ["#e8dbb7", "#ae835b", "#b15533", "#ffffff"],
    detailCopy:
      "The standing acorn form is a compact lidded object that makes spare keys, jewelry, or a small gift feel deliberately placed rather than tucked away.",
    highlights: [
      "Maker-listed size: 120 mm tall × 80 mm wide",
      "Standing form with a compact screw-top lid",
      "Four curated base-and-cap colorways",
      "No hardware or AMS required",
    ],
    fitNote:
      "The creator recommends the supplied profile for the screw-top fit. Each colorway is made from two separately finished pieces.",
    material: "Bambu PLA Matte",
    finish: "Fine ribbing with a fuzzy-textured screw cap",
    care: "Wipe with a soft, damp cloth. Keep away from sustained heat and direct sunlight.",
    leadTime: "Printed to order in 3–5 business days",
    designerName: "SabreDesign",
    designerUrl: "https://makerworld.com/en/@SabreDesign",
    sourceModelUrl: "https://makerworld.com/en/models/1701607-acorn-containers#profileId-1804557",
    requiresCommercialLicense: true,
    licenseStatus: "active",
    demo: false,
    variants: [
      {
        priceId: "pending_acorn_container",
        sizeLabel: "Standing · 120 mm",
        unitAmount: 2500,
        currency: "usd",
        sku: "ACN-STANDING",
        dimensions: "120 mm tall × 80 mm wide",
      },
    ],
  },
  {
    id: "local-preview-japandi-mushroom-container",
    slug: "japandi-mushroom-container",
    name: "Japandi Mushroom Container",
    description:
      "A small, sculptural mushroom that twists open to keep tiny treasures close at hand.",
    category: "Home",
    colors: ["Sandstone", "Forest", "Blush", "Graphite"],
    colorways: [
      {
        label: "Sandstone",
        baseColor: "Matte Desert Tan (11401)",
        baseHex: "#e8dbb7",
        capColor: "Matte Ivory White (11100)",
        capHex: "#ffffff",
      },
      {
        label: "Forest",
        baseColor: "Matte Desert Tan (11401)",
        baseHex: "#e8dbb7",
        capColor: "Matte Dark Green (11501)",
        capHex: "#68724d",
      },
      {
        label: "Blush",
        baseColor: "Matte Ivory White (11100)",
        baseHex: "#ffffff",
        capColor: "Matte Sakura Pink (11201)",
        capHex: "#e4bdd0",
      },
      {
        label: "Graphite",
        baseColor: "Matte Ash Gray (11102)",
        baseHex: "#9b9ea0",
        capColor: "Matte Charcoal (11101)",
        capHex: "#000000",
      },
    ],
    featured: false,
    pickup: true,
    ship: true,
    stockStatus: "made_to_order",
    visibility: "public",
    photoReady: true,
    image: sabreDesignMushroomContainerImages[0],
    images: [...sabreDesignMushroomContainerImages],
    accent: "rose",
    colorHexes: ["#e8dbb7", "#e8dbb7", "#ffffff", "#9b9ea0"],
    detailCopy:
      "This compact container brings a little warmth to a nightstand, shelf, or entry table. Its ribbed base and textured cap twist together without any additional hardware.",
    highlights: [
      "Maker-listed size: 73 mm tall × 70 mm wide",
      "Two printed parts with a twist-together lid",
      "Four curated base-and-cap colorways",
      "No hardware or AMS required",
    ],
    fitNote:
      "The twist-together lid is made from two separately finished pieces for each selected colorway.",
    material: "Bambu PLA Matte",
    finish: "Fine ribbing below a soft fuzzy-textured cap",
    care: "Wipe with a soft, damp cloth. Keep away from sustained heat and direct sunlight.",
    leadTime: "Printed to order in 3–5 business days",
    designerName: "SabreDesign",
    designerUrl: "https://makerworld.com/en/@SabreDesign",
    sourceModelUrl: "https://makerworld.com/en/models/1821679-japandi-mushroom-decoration-container#profileId-1944539",
    requiresCommercialLicense: true,
    licenseStatus: "active",
    demo: false,
    variants: [
      {
        priceId: "pending_japandi_mushroom_container",
        sizeLabel: "73 mm mushroom",
        unitAmount: 2000,
        currency: "usd",
        sku: "JMC-STANDARD",
        dimensions: "73 mm tall × 70 mm wide",
      },
    ],
  },
  {
    id: "local-preview-juno-display-tray",
    slug: "juno-display-tray",
    name: "Juno Storage Tray",
    description:
      "A large, architectural tray with a concealed twist-lock compartment for keeping small essentials neatly out of sight.",
    category: "Home",
    colors: ["Matte Charcoal", "Matte Ivory White", "Matte Desert Tan", "Matte Dark Green"],
    featured: false,
    pickup: true,
    ship: true,
    stockStatus: "made_to_order",
    visibility: "public",
    photoReady: true,
    image: sabreDesignJunoTrayImages[0],
    images: [...sabreDesignJunoTrayImages],
    accent: "graphite",
    colorHexes: ["#000000", "#ffffff", "#e8dbb7", "#68724d"],
    detailCopy:
      "The two-piece Juno pairs a sculptural display lid with a roomy base. A twist-lock connection keeps jewelry, keys, keepsakes, and other small essentials tucked away beneath its architectural top.",
    highlights: [
      "Maker-listed footprint: 236 mm wide",
      "Two-piece tray with a twist-lock storage compartment",
      "Current X2D slice: 2 plates · 9 hours 56 minutes · 368.35 g",
      "Hidden storage beneath a sculptural display surface",
    ],
    fitNote:
      "At 236 mm wide, this tray uses nearly the full main print area. The lid twists onto the base to close the storage compartment.",
    material: "Bambu PLA Matte",
    finish: "Fine matte surfaces with a fitted twist-lock lid and hand-checked edges",
    care: "Decorative storage only. Wipe with a soft, damp cloth and avoid sustained heat.",
    leadTime: "Printed to order in 3–5 business days",
    designerName: "SabreDesign",
    designerUrl: "https://makerworld.com/en/@SabreDesign",
    sourceModelUrl: "https://makerworld.com/en/models/2841008-juno-tray#profileId-3167196",
    requiresCommercialLicense: true,
    licenseStatus: "active",
    demo: false,
    variants: [
      {
        priceId: "pending_juno_display_tray",
        sizeLabel: "Two-piece storage · 236 mm",
        unitAmount: 4200,
        currency: "usd",
        sku: "JUNO-STORAGE",
        dimensions: "236 mm-wide two-piece twist-lock storage tray",
      },
    ],
  },
  {
    id: "local-preview-sculptural-phone-stand",
    slug: "sculptural-phone-stand",
    name: "Sculptural Phone Stand",
    description:
      "A weighty, flowing phone stand that keeps a device useful at the desk and handsome when it is empty.",
    category: "Desk",
    colors: [
      "Matte Ivory White (11100)",
      "Matte Charcoal (11101)",
      "Matte Dark Blue (11602)",
      "Matte Sakura Pink (11201)",
      "Matte Apple Green (11502)",
    ],
    featured: false,
    pickup: true,
    ship: true,
    stockStatus: "made_to_order",
    visibility: "public",
    photoReady: true,
    image: sabreDesignPhoneStandImages[0],
    images: [...sabreDesignPhoneStandImages],
    accent: "ocean",
    colorHexes: ["#ffffff", "#000000", "#042f56", "#e4bdd0", "#c2e189"],
    detailCopy:
      "This minimal stand gives a phone a stable home while working, cooking, or following along with a video. The original profile uses a heavier build so the stand stays planted while the screen is tapped.",
    highlights: [
      "Original creator profile: 1 plate · about 3.3 hours",
      "Heavier 6-wall build for a more planted feel",
      "Designed for a wide range of phones and thicker cases",
      "Single-color print with no hardware or AMS required",
    ],
    fitNote:
      "MakerWorld does not publish a dimensional spec for this model. It is designed for a wide range of phones and thicker cases.",
    material: "Bambu PLA Matte",
    finish: "Fine matte surface with flowing, minimal contours",
    care: "Wipe with a soft, damp cloth. Keep away from sustained heat and direct sunlight.",
    leadTime: "Printed to order in 3–5 business days",
    designerName: "SabreDesign",
    designerUrl: "https://makerworld.com/en/@SabreDesign",
    sourceModelUrl: "https://makerworld.com/en/models/717070-phone-stand#profileId-647981",
    requiresCommercialLicense: true,
    licenseStatus: "active",
    demo: false,
    variants: [
      {
        priceId: "pending_sculptural_phone_stand",
        sizeLabel: "One size",
        unitAmount: 2400,
        currency: "usd",
        sku: "SPS-STANDARD",
      },
    ],
  },
];
