import type { StoreProduct } from "./types";

export const demoProducts: StoreProduct[] = [
  {
    id: "demo-wave-planter",
    slug: "wave-planter",
    name: "Wave Planter",
    description:
      "A softly ribbed desktop planter with a watertight liner and a layered finish that catches the light.",
    category: "Home",
    colors: ["Terracotta", "Sage", "Sand"],
    featured: true,
    pickup: true,
    ship: true,
    stockStatus: "made_to_order",
    image: "/products/wave-planter-demo.png",
    images: ["/products/wave-planter-demo.png"],
    accent: "clay",
    colorHexes: ["#b76649", "#879b76", "#cdbb97"],
    detailCopy: "The rounded ribs soften the planter's silhouette while giving the print a steady grip. A removable liner protects the outer shell and makes watering less fussy.",
    highlights: ["Removable watertight liner", "Light-catching ribbed surface", "Sized for desks and narrow shelves"],
    material: "Plant-based PLA with a separate watertight liner",
    finish: "Soft matte surface with visible horizontal layer texture",
    care: "Remove the liner to water. Wipe the outer shell clean and keep away from high heat.",
    leadTime: "Printed to order in 3–5 business days",
    demo: true,
    variants: [
      { priceId: "demo_wave_small", sizeLabel: "Small · 4 in", unitAmount: 1800, currency: "usd", sku: "WAVE-S", dimensions: "4 in diameter × 4 in high" },
      { priceId: "demo_wave_large", sizeLabel: "Large · 6 in", unitAmount: 2600, currency: "usd", sku: "WAVE-L", dimensions: "6 in diameter × 6 in high" },
    ],
  },
  {
    id: "demo-dragon",
    slug: "articulated-dragon",
    name: "Articulated Dragon",
    description:
      "A satisfyingly flexible display piece with print-in-place joints and expressive scale details.",
    category: "Play",
    colors: ["Copper", "Ocean", "Galaxy"],
    featured: true,
    pickup: true,
    ship: true,
    stockStatus: "in_stock",
    image: "/products/articulated-dragon-demo.png",
    images: ["/products/articulated-dragon-demo.png"],
    accent: "ocean",
    colorHexes: ["#a86642", "#3e7484", "#524b73"],
    detailCopy: "Every joint prints already connected, so the dragon moves straight off the print bed. The segmented body coils easily without loose pins or assembly hardware.",
    highlights: ["Print-in-place moving joints", "No assembly or loose hardware", "Flexible display and fidget piece"],
    material: "Durable PLA selected for clean joint movement",
    finish: "Detailed scales with hand-checked articulation",
    care: "Move joints gently at first. Keep away from high heat and children under three.",
    leadTime: "Usually ready in 1–3 business days",
    demo: true,
    variants: [
      { priceId: "demo_dragon_mini", sizeLabel: "Mini · 8 in", unitAmount: 1600, currency: "usd", sku: "DRGN-MINI", dimensions: "About 8 × 2.25 × 1.5 in" },
      { priceId: "demo_dragon_full", sizeLabel: "Full · 16 in", unitAmount: 2800, currency: "usd", sku: "DRGN-FULL", dimensions: "About 16 × 4.5 × 3 in" },
    ],
  },
  {
    id: "demo-controller-dock",
    slug: "controller-dock",
    name: "Controller Dock",
    description:
      "A balanced display stand that keeps your controller upright, easy to grab, and off the desk.",
    category: "Desk",
    colors: ["Graphite", "Bone", "Safety Orange"],
    featured: true,
    pickup: true,
    ship: true,
    stockStatus: "made_to_order",
    image: "/products/controller-dock-demo.png",
    images: ["/products/controller-dock-demo.png"],
    accent: "graphite",
    colorHexes: ["#4f5652", "#d8d0bf", "#df642c"],
    detailCopy: "The angled cradle supports a controller at its strongest points and keeps the charging port clear. A broad footprint resists tipping without taking over the desk.",
    highlights: ["Stable weighted stance", "Charging-port clearance", "Soft contact points protect the controller"],
    material: "PLA body with non-marking contact pads",
    finish: "Low-sheen body with clean support surfaces",
    care: "Wipe clean with a damp cloth. Keep away from direct heat and open flame.",
    leadTime: "Printed to order in 3–5 business days",
    demo: true,
    variants: [
      { priceId: "demo_dock_standard", sizeLabel: "Standard", unitAmount: 2200, currency: "usd", sku: "DOCK-STD", dimensions: "4.5 × 3.75 × 5.5 in" },
    ],
  },
  {
    id: "demo-hex-tray",
    slug: "hex-catchall-tray",
    name: "Hex Catchall Tray",
    description:
      "A modular tray for keys, coins, earbuds, and the small things that otherwise wander across your desk.",
    category: "Desk",
    colors: ["Moss", "Charcoal", "Cream"],
    featured: false,
    pickup: true,
    ship: true,
    stockStatus: "in_stock",
    image: "/products/hex-catchall-tray-demo.png",
    images: ["/products/hex-catchall-tray-demo.png"],
    accent: "moss",
    colorHexes: ["#748660", "#414844", "#ded6be"],
    detailCopy: "The shallow hex profile corrals pocket items without hiding them. Flat sides let several trays sit together in a tidy honeycomb when your setup grows.",
    highlights: ["Modular flat-sided shape", "Shallow easy-reach rim", "Works alone or in grouped layouts"],
    material: "Plant-based PLA",
    finish: "Matte base with a fine visible layer pattern",
    care: "Wipe clean with a soft, damp cloth. Not intended for food contact or high heat.",
    leadTime: "Usually ready in 1–3 business days",
    demo: true,
    variants: [
      { priceId: "demo_hex_single", sizeLabel: "Single", unitAmount: 1400, currency: "usd", sku: "HEX-1", dimensions: "6 × 5.25 × 0.75 in" },
      { priceId: "demo_hex_pair", sizeLabel: "Pair", unitAmount: 2400, currency: "usd", sku: "HEX-2", dimensions: "Two trays, each 6 × 5.25 × 0.75 in" },
    ],
  },
  {
    id: "demo-book-nook",
    slug: "book-nook-marker-set",
    name: "Book Nook Markers",
    description:
      "A set of sculptural page markers designed to peek over your shelf without bending a favorite book.",
    category: "Gifts",
    colors: ["Rose", "Lavender", "Cobalt"],
    featured: false,
    pickup: true,
    ship: true,
    stockStatus: "made_to_order",
    image: "/products/book-nook-markers-demo.png",
    images: ["/products/book-nook-markers-demo.png"],
    accent: "rose",
    colorHexes: ["#b96e70", "#9b8bb2", "#355d9d"],
    detailCopy: "Each marker rests lightly between pages while its small sculpted top stays visible above the book. The thin profile marks your place without folding a corner.",
    highlights: ["Slim page-safe profile", "Three markers per set", "Sculpted tops stay easy to spot"],
    material: "Lightweight PLA",
    finish: "Smooth face with a crisp sculpted top",
    care: "Slide out before closing or stacking books tightly. Keep away from high heat.",
    leadTime: "Printed to order in 3–5 business days",
    demo: true,
    variants: [
      { priceId: "demo_markers_three", sizeLabel: "Set of 3", unitAmount: 1200, currency: "usd", sku: "MARK-3", dimensions: "About 2.5 × 1.25 in each" },
    ],
  },
  {
    id: "demo-cable-combs",
    slug: "cable-comb-set",
    name: "Cable Comb Set",
    description:
      "Low-profile clips that turn a tangle of charging cables into a clean, repeatable desk setup.",
    category: "Desk",
    colors: ["Graphite", "Mint", "Signal Yellow"],
    featured: false,
    pickup: true,
    ship: true,
    stockStatus: "sold_out",
    image: "/products/cable-comb-set-demo.png",
    images: ["/products/cable-comb-set-demo.png"],
    accent: "yellow",
    colorHexes: ["#4f5652", "#89b7a6", "#d5aa2f"],
    detailCopy: "The low-profile channels hold everyday charging cables in parallel so they stay separated and return to the same place after use.",
    highlights: ["Six clips per set", "Low-profile desk footprint", "Flexible channels for common charging cables"],
    material: "PLA with flex-tuned cable channels",
    finish: "Smooth top face with rounded cable entries",
    care: "Press cables in from above rather than pulling them through. Keep away from high heat.",
    leadTime: "Currently unavailable",
    demo: true,
    variants: [
      { priceId: "demo_cable_six", sizeLabel: "Set of 6", unitAmount: 1000, currency: "usd", sku: "CABLE-6", dimensions: "About 1.5 × 0.65 × 0.3 in each" },
    ],
  },
];
