import type { StoreProduct } from "./types";

export const demoProducts: StoreProduct[] = [
  {
    id: "demo-wave-planter",
    slug: "wave-planter",
    name: "Wave Planter",
    description:
      "A softly ribbed desktop planter with a watertight liner and a layered finish that catches the light.",
    category: "Home",
    colors: ["Terracotta", "Sage", "Sand"],
    featured: true,
    pickup: true,
    ship: true,
    stockStatus: "made_to_order",
    image: "/products/wave-planter-demo.png",
    accent: "clay",
    demo: true,
    variants: [
      { priceId: "demo_wave_small", sizeLabel: "Small · 4 in", unitAmount: 1800, currency: "usd", sku: "WAVE-S" },
      { priceId: "demo_wave_large", sizeLabel: "Large · 6 in", unitAmount: 2600, currency: "usd", sku: "WAVE-L" },
    ],
  },
  {
    id: "demo-dragon",
    slug: "articulated-dragon",
    name: "Articulated Dragon",
    description:
      "A satisfyingly flexible display piece with print-in-place joints and expressive scale details.",
    category: "Play",
    colors: ["Copper", "Ocean", "Galaxy"],
    featured: true,
    pickup: true,
    ship: true,
    stockStatus: "in_stock",
    image: "/products/articulated-dragon-demo.png",
    accent: "ocean",
    demo: true,
    variants: [
      { priceId: "demo_dragon_mini", sizeLabel: "Mini · 8 in", unitAmount: 1600, currency: "usd", sku: "DRGN-MINI" },
      { priceId: "demo_dragon_full", sizeLabel: "Full · 16 in", unitAmount: 2800, currency: "usd", sku: "DRGN-FULL" },
    ],
  },
  {
    id: "demo-controller-dock",
    slug: "controller-dock",
    name: "Controller Dock",
    description:
      "A balanced display stand that keeps your controller upright, easy to grab, and off the desk.",
    category: "Desk",
    colors: ["Graphite", "Bone", "Safety Orange"],
    featured: true,
    pickup: true,
    ship: true,
    stockStatus: "made_to_order",
    image: "/products/controller-dock-demo.png",
    accent: "graphite",
    demo: true,
    variants: [
      { priceId: "demo_dock_standard", sizeLabel: "Standard", unitAmount: 2200, currency: "usd", sku: "DOCK-STD" },
    ],
  },
  {
    id: "demo-hex-tray",
    slug: "hex-catchall-tray",
    name: "Hex Catchall Tray",
    description:
      "A modular tray for keys, coins, earbuds, and the small things that otherwise wander across your desk.",
    category: "Desk",
    colors: ["Moss", "Charcoal", "Cream"],
    featured: false,
    pickup: true,
    ship: true,
    stockStatus: "in_stock",
    image: "/products/hex-catchall-tray-demo.png",
    accent: "moss",
    demo: true,
    variants: [
      { priceId: "demo_hex_single", sizeLabel: "Single", unitAmount: 1400, currency: "usd", sku: "HEX-1" },
      { priceId: "demo_hex_pair", sizeLabel: "Pair", unitAmount: 2400, currency: "usd", sku: "HEX-2" },
    ],
  },
  {
    id: "demo-book-nook",
    slug: "book-nook-marker-set",
    name: "Book Nook Markers",
    description:
      "A set of sculptural page markers designed to peek over your shelf without bending a favorite book.",
    category: "Gifts",
    colors: ["Rose", "Lavender", "Cobalt"],
    featured: false,
    pickup: true,
    ship: true,
    stockStatus: "made_to_order",
    image: "/products/book-nook-markers-demo.png",
    accent: "rose",
    demo: true,
    variants: [
      { priceId: "demo_markers_three", sizeLabel: "Set of 3", unitAmount: 1200, currency: "usd", sku: "MARK-3" },
    ],
  },
  {
    id: "demo-cable-combs",
    slug: "cable-comb-set",
    name: "Cable Comb Set",
    description:
      "Low-profile clips that turn a tangle of charging cables into a clean, repeatable desk setup.",
    category: "Desk",
    colors: ["Graphite", "Mint", "Signal Yellow"],
    featured: false,
    pickup: true,
    ship: true,
    stockStatus: "sold_out",
    image: "/products/cable-comb-set-demo.png",
    accent: "yellow",
    demo: true,
    variants: [
      { priceId: "demo_cable_six", sizeLabel: "Set of 6", unitAmount: 1000, currency: "usd", sku: "CABLE-6" },
    ],
  },
];
